// APQC Process Classification Framework navigation levels above Progress
// ID. Process Step IDs already encode this - e.g. "9.6.1.1" is Category 9,
// Process Group 9.6, Process 9.6.1, Activity 9.6.1.1 - these just truncate
// to fewer segments, same technique getProgressId (in models/IProcessStep.ts)
// already uses for 3 segments.

export function getCategoryId(processStepId: string): string {
  return (processStepId || '').split('.').slice(0, 1).join('.');
}

export function getProcessGroupId(processStepId: string): string {
  return (processStepId || '').split('.').slice(0, 2).join('.');
}

// Two different confidence levels living in the same table - kept
// distinct here rather than pretending they're equivalent:
//
// 1, 7, 8, 9, 11, 12, 13: transcribed directly from the user's own
// reference sheet (Category/Process Group/Process, PDF text extracted
// verbatim, not OCR'd off a screenshot) - see APQC_PROCESS_GROUP_NAMES/
// APQC_PROGRESS_ID_NAMES below for the full verified breakdown of these.
//
// 2, 3, 4, 5, 6, 10: added 2026-08-19 from the standard published APQC
// Cross-Industry Process Classification Framework, NOT from a QLE-
// specific reference document the way the others were - there isn't one
// for these categories yet. Category-level names only; deliberately no
// Process Group/Progress ID entries added underneath them, since
// fabricating that level of sub-classification from general knowledge
// risks presenting made-up detail as if it were verified reference data
// (exactly the kind of thing that already caused a real bug once - see
// the precedence-fix commit from 2026-08-18). Build these out for real
// via "+ Add new process group"/"+ Add new progress ID" as needed, or
// swap this comment out once a real reference sheet exists for them.
export const APQC_CATEGORY_NAMES: Record<string, string> = {
  '1': 'Develop Vision and Strategy',
  '2': 'Develop and Manage Products and Services',
  '3': 'Market and Sell Products and Services',
  '4': 'Deliver Physical Products',
  '5': 'Deliver Services',
  '6': 'Manage Customer Service',
  '7': 'Develop and Manage Human Resources',
  '8': 'Manage Information Technology (IT)',
  '9': 'Manage Financial Resources',
  '10': 'Acquire, Construct, and Manage Assets',
  '11': 'Manage Enterprise Risk, Compliance, Remediation, and Resiliency',
  '12': 'Manage External Relationships',
  '13': 'Develop and Manage Business Capabilities'
};

export const APQC_PROCESS_GROUP_NAMES: Record<string, string> = {
  '1.1': 'Define the business concept and long-term vision',
  '1.2': 'Develop business strategy',
  '1.3': 'Develop and measure strategic initiatives',
  '1.4': 'Develop and maintain business models',

  '7.1': 'Develop and manage human resources (HR) planning, policies, and strategies',
  '7.2': 'Recruit, source, and select employees',
  '7.3': 'Manage employee onboarding, training, and development',
  '7.4': 'Manage employee relations',
  '7.5': 'Reward and retain employees',
  '7.6': 'Redeploy and retire employees',
  '7.7': 'Manage employee information and analytics',
  '7.8': 'Manage employee communication',

  '8.1': 'Develop and manage IT customer relationships',
  '8.2': 'Develop and manage IT business strategy',
  '8.3': 'Develop and manage IT resilience and risk',
  '8.4': 'Manage information',
  '8.5': 'Develop and manage services/solutions',
  '8.6': 'Deploy services/solutions',
  '8.7': 'Create and manage support services/solutions',

  '9.1': 'Perform planning and management accounting',
  '9.2': 'Perform revenue accounting',
  '9.3': 'Perform general accounting and reporting',
  '9.4': 'Manage fixed-asset project accounting',
  '9.5': 'Process payroll',
  '9.6': 'Process accounts payable and expense reimbursements',
  '9.7': 'Manage treasury operations',
  '9.8': 'Manage internal controls',
  '9.9': 'Manage taxes',
  '9.10': 'Manage international funds/consolidation',
  '9.11': 'Perform global trade services',

  '11.1': 'Manage enterprise risk',
  '11.2': 'Manage compliance',
  '11.3': 'Manage remediation efforts',
  '11.4': 'Manage business resiliency',

  '12.1': 'Build investor relationships',
  '12.2': 'Manage government and industry relationships',
  '12.3': 'Manage relations with board of directors',
  '12.4': 'Manage legal and ethical issues',
  '12.5': 'Manage public relations program',

  '13.1': 'Manage business processes',
  '13.2': 'Manage portfolio, program, and project',
  '13.3': 'Manage enterprise quality',
  '13.4': 'Manage change',
  '13.5': 'Develop and manage enterprise-wide knowledge management (KM) capability',
  '13.6': 'Manage Content',
  '13.7': 'Measure and benchmark',
  '13.8': 'Develop, Manage, and Deliver Analytics',
  '13.9': 'Manage Environmental Health and Safety (EHS)',
  '13.10': 'Manage sustainability'
};

// Progress ID (3-segment) names - the "Process" level of the reference
// sheet, one level below Process Group. Used as a fallback label for the
// Progress ID picker when a group has no steps loaded yet to read
// processDescription from (see getLabel in SwimlaneStudio.tsx).
export const APQC_PROGRESS_ID_NAMES: Record<string, string> = {
  '1.1.1': 'Assess the external environment',
  '1.1.2': 'Survey market and determine customer needs and wants',
  '1.1.3': 'Assess the internal environment',
  '1.1.4': 'Establish strategic vision',
  '1.1.5': 'Conduct organization restructuring opportunities',
  '1.2.1': 'Develop overall mission statement',
  '1.2.2': 'Define and evaluate strategic options to achieve the mission',
  '1.2.3': 'Set/Develop long-term enterprise strategy',
  '1.2.4': 'Coordinate and align cross-functional and process strategies',
  '1.2.5': 'Create organizational design',
  '1.2.6': 'Develop and set organizational objectives',
  '1.2.7': 'Formulate business unit strategies',
  '1.2.8': 'Develop customer experience strategy',
  '1.2.9': 'Communicate strategies internally and externally',
  '1.3.1': 'Develop strategic initiatives',
  '1.3.2': 'Evaluate strategic initiatives',
  '1.3.3': 'Select strategic initiatives',
  '1.3.4': 'Establish high-level measures',
  '1.3.5': 'Execute strategic initiatives',
  '1.3.6': 'Review execution of strategic initiatives',
  '1.3.7': 'Refine strategic initiatives and project plans as needed',
  '1.4.1': 'Develop business models',
  '1.4.2': 'Maintain business models',
  '1.4.3': 'Establish business model governance',

  '7.1.1': 'Develop human resources strategy',
  '7.1.2': 'Develop and implement workforce planning, policies, and strategies',
  '7.1.3': 'Monitor and update HR strategies, plans, and policies',
  '7.1.4': 'Develop competency management models',
  '7.2.1': 'Manage employee requisitions',
  '7.2.2': 'Recruit/Source candidates',
  '7.2.3': 'Screen and select candidates',
  '7.2.4': 'Manage new hire/re-hire',
  '7.2.5': 'Manage applicant information',
  '7.3.1': 'Manage employee onboarding',
  '7.3.2': 'Manage employee performance',
  '7.3.3': 'Manage employee career development',
  '7.3.4': 'Develop and train employees',
  '7.4.1': 'Manage labor relations',
  '7.4.2': 'Manage collective bargaining process',
  '7.4.3': 'Manage labor management partnerships',
  '7.4.4': 'Manage employee grievances',
  '7.4.5': 'Monitor legal and regulatory environment',
  '7.5.1': 'Develop and manage reward, recognition, and motivation programs',
  '7.5.2': 'Manage and administer benefits',
  '7.5.3': 'Manage employee assistance and retention',
  '7.5.4': 'Administer Payroll',
  '7.5.5': 'Manage/Collect employee suggestions and perform employee research',
  '7.6.1': 'Manage promotion and demotion process',
  '7.6.2': 'Manage separation',
  '7.6.3': 'Relocate employees and manage assignments',
  '7.7.1': 'Manage reporting processes',
  '7.7.2': 'Manage employee inquiry process',
  '7.7.3': 'Manage and maintain employee data',
  '7.7.4': 'Manage human resource information systems',
  '7.7.5': 'Develop and manage employee measures',
  '7.7.6': 'Develop and manage time and attendance systems',
  '7.7.7': 'Develop workforce analytics',
  '7.7.8': 'Implement workforce analytics',
  '7.8.1': 'Develop employee communication plan',
  '7.8.2': 'Conduct employee engagement surveys',
  '7.8.3': 'Deliver employee communications',

  '8.1.1': 'Understand IT customer needs',
  '8.1.2': 'Identify IT customer transformation needs',
  '8.1.3': 'Plan and communicate IT services',
  '8.1.4': 'Provide IT transformation guidance',
  '8.1.5': 'Develop and manage IT service levels',
  '8.1.6': 'Manage IT customer relationships',
  '8.1.7': 'Analyze service performance',
  '8.2.1': 'Define business technology and governance strategy',
  '8.2.2': 'Manage IT portfolio strategy',
  '8.2.3': 'Define and maintain enterprise architecture',
  '8.2.4': 'Define IT service management strategy',
  '8.2.5': 'Control IT management system',
  '8.2.6': 'Manage IT value portfolio',
  '8.2.7': 'Define and manage technology innovation',
  '8.3.1': 'Develop IT compliance, risk, and security strategy',
  '8.3.2': 'Develop IT resilience strategy',
  '8.3.3': 'Control IT risk, compliance, and security',
  '8.3.4': 'Plan and manage IT continuity',
  '8.3.5': 'Develop and manage IT security, privacy, and data protection',
  '8.3.6': 'Conduct and analyze IT compliance assessments',
  '8.3.7': 'Develop and execute IT resilience and continuity operations',
  '8.3.8': 'Manage IT user identity and authorization',
  '8.4.1': 'Define business information and analytics strategy',
  '8.4.2': 'Define and maintain business information architecture',
  '8.4.3': 'Define and execute business information lifecycle planning and control',
  '8.4.4': 'Manage business information',
  '8.5.1': 'Develop service/solution and integration strategy',
  '8.5.2': 'Manage service/solution lifecycle planning',
  '8.5.3': 'Develop and manage service/solution architecture',
  '8.5.4': 'Execute IT service/solution creation and testing',
  '8.5.5': 'Perform service/solution maintenance and testing',
  '8.6.1': 'Develop and manage service/solution deployment strategy',
  '8.6.2': 'Plan service and solution implementation',
  '8.6.3': 'Manage change deployment control',
  '8.6.4': 'Implement technology solutions',
  '8.6.5': 'Perform service and solution rollout',
  '8.7.1': 'Define and establish service delivery strategy',
  '8.7.2': 'Define and develop service support strategy',
  '8.7.3': 'Plan and manage service delivery control',
  '8.7.4': 'Develop and manage infrastructure resource planning',
  '8.7.5': 'Define service support planning',
  '8.7.6': 'Develop and manage service delivery operations',
  '8.7.7': 'Manage infrastructure resource administration',
  '8.7.8': 'Operate IT user support',

  '9.1.1': 'Develop and manage financial resources strategy',
  '9.1.2': 'Perform planning/budgeting/forecasting',
  '9.1.3': 'Perform cost accounting and control',
  '9.1.4': 'Perform cost management',
  '9.1.5': 'Evaluate and manage financial performance',
  '9.2.1': 'Process customer credit',
  '9.2.2': 'Invoice customer',
  '9.2.3': 'Process accounts receivable (AR)',
  '9.2.4': 'Manage and process collections',
  '9.2.5': 'Manage and process adjustments/deductions',
  '9.3.1': 'Manage financial policies and procedures',
  '9.3.2': 'Perform general accounting',
  '9.3.3': 'Perform fixed-asset accounting',
  '9.3.4': 'Perform financial reporting',
  '9.4.1': 'Perform capital planning and project approval',
  '9.4.2': 'Perform capital project accounting',
  '9.5.1': 'Report time',
  '9.5.2': 'Manage pay',
  '9.5.3': 'Manage and process payroll taxes',
  '9.6.1': 'Process accounts payable (AP)',
  '9.6.2': 'Process expense reimbursements',
  '9.6.3': 'Manage corporate credit cards',
  '9.7.1': 'Manage treasury policies and procedures',
  '9.7.2': 'Manage cash',
  '9.7.3': 'Manage in-house bank accounts',
  '9.7.4': 'Manage debt and investment',
  '9.7.5': 'Monitor and execute risk and hedging transactions',
  '9.7.6': 'Manage financial fraud/dispute cases',
  '9.8.1': 'Establish internal controls, policies, and procedures',
  '9.8.2': 'Operate controls and monitor compliance with internal controls policies and procedures',
  '9.8.3': 'Report on internal controls compliance',
  '9.9.1': 'Develop tax strategy and plan',
  '9.9.2': 'Process taxes',
  '9.10.1': 'Monitor international rates',
  '9.10.2': 'Manage transactions',
  '9.10.3': 'Monitor currency exposure/hedge currency',
  '9.10.4': 'Report results',
  '9.11.1': 'Screen sanctioned party list',
  '9.11.2': 'Control exports and imports',
  '9.11.3': 'Classify products',
  '9.11.4': 'Perform currency conversion',
  '9.11.5': 'Calculate duty',
  '9.11.6': 'Communicate with customs',
  '9.11.7': 'Document trade',
  '9.11.8': 'Process trade preferences',
  '9.11.9': 'Handle restitution',
  '9.11.10': 'Prepare letter of credit',

  '11.1.1': 'Establish the enterprise risk framework and policies',
  '11.1.2': 'Oversee and coordinate enterprise risk management activities',
  '11.1.3': 'Manage business unit and function risk',
  '11.2.1': 'Establish compliance framework and policies',
  '11.2.2': 'Manage regulatory compliance',
  '11.3.1': 'Create remediation plans',
  '11.3.2': 'Contact and confer with experts',
  '11.3.3': 'Identify/Dedicate resources',
  '11.3.4': 'Investigate legal aspects',
  '11.3.5': 'Investigate damage cause',
  '11.3.6': 'Amend or create policy',
  '11.4.1': 'Develop the business resilience strategy',
  '11.4.2': 'Perform continuous business operations planning',
  '11.4.3': 'Test continuous business operations',
  '11.4.4': 'Maintain continuous business operations',
  '11.4.5': 'Share knowledge of specific risks across other parts of the organization',

  '12.1.1': 'Plan, build, and manage lender relations',
  '12.1.2': 'Plan, build, and manage analyst relations',
  '12.1.3': 'Communicate with shareholders',
  '12.2.1': 'Manage government relations',
  '12.2.2': 'Manage relations with quasi-government bodies',
  '12.2.3': 'Manage relations with trade or industry groups',
  '12.2.4': 'Manage lobby activities',
  '12.3.1': 'Report financial results',
  '12.3.2': 'Report audit findings',
  '12.4.1': 'Create ethics policies',
  '12.4.2': 'Manage corporate governance policies',
  '12.4.3': 'Develop and perform preventive law programs',
  '12.4.4': 'Ensure compliance',
  '12.4.5': 'Manage outside counsel',
  '12.4.6': 'Protect intellectual property',
  '12.4.7': 'Resolve disputes and litigations',
  '12.4.8': 'Provide legal advice/counseling',
  '12.4.9': 'Negotiate and document agreements/contracts',
  '12.5.1': 'Manage community relations',
  '12.5.2': 'Manage media relations',
  '12.5.3': 'Promote political stability',
  '12.5.4': 'Create press releases',
  '12.5.5': 'Issue press releases',

  '13.1.1': 'Establish and maintain process management governance',
  '13.1.2': 'Define and manage process frameworks',
  '13.1.3': 'Define processes',
  '13.1.4': 'Manage process performance',
  '13.1.5': 'Improve processes',
  '13.2.1': 'Manage portfolio',
  '13.2.2': 'Manage programs',
  '13.2.3': 'Manage projects',
  '13.3.1': 'Establish quality requirements',
  '13.3.2': 'Evaluate performance to requirements',
  '13.3.3': 'Manage non-conformance',
  '13.3.4': 'Implement and maintain the enterprise quality management system (EQMS)',
  '13.4.1': 'Plan for change',
  '13.4.2': 'Design the change',
  '13.4.3': 'Implement change',
  '13.4.4': 'Sustain improvement',
  '13.5.1': 'Develop KM strategy',
  '13.5.2': 'Assess KM capabilities',
  '13.5.3': 'Design and implement KM capabilities',
  '13.5.4': 'Evolve and sustain KM capabilities',
  '13.6.1': 'Define content management strategy',
  '13.6.2': 'Develop and manage taxonomies',
  '13.6.3': 'Define content systems of record and storage requirements',
  '13.6.4': 'Manage content infrastructure',
  '13.6.5': 'Develop and manage content',
  '13.6.6': 'Deliver approved content',
  '13.6.7': 'Control delivered content',
  '13.7.1': 'Define and manage organizational performance strategy',
  '13.7.2': 'Benchmark performance',
  '13.7.3': 'Evaluate performance',
  '13.8.1': 'Identify needs from stakeholders',
  '13.8.2': 'Scope analytics project',
  '13.8.3': 'Develop and manage hypotheses',
  '13.8.4': 'Collect data',
  '13.8.5': 'Prepare data',
  '13.8.6': 'Analyze data',
  '13.8.7': 'Create data models',
  '13.8.8': 'Review data models with stakeholders',
  '13.8.9': 'Refine data models',
  '13.8.10': 'Report on analysis',
  '13.8.11': 'Identify remedial actions',
  '13.9.1': 'Determine environmental health and safety impacts',
  '13.9.2': 'Develop EHS program',
  '13.9.3': 'Monitor and manage EHS program',
  '13.10.1': 'Develop sustainability capability',
  '13.10.2': 'Manage sustainability capability'
};

export function getCategoryName(categoryId: string): string {
  return APQC_CATEGORY_NAMES[categoryId] || `Category ${categoryId}`;
}

export function getProcessGroupName(groupId: string): string {
  return APQC_PROCESS_GROUP_NAMES[groupId] || `Process Group ${groupId}`;
}

export function getProgressIdName(progressId: string): string {
  return APQC_PROGRESS_ID_NAMES[progressId] || `Progress ID ${progressId}`;
}
